// Copyright © Erickson Lopez. MIT License.
using System;
using System.IO;
using System.Linq;
using System.Reflection;
using EricksonLopez.Events.Contracts;
using EricksonLopez.Events.Generators;
using EricksonLopez.Events.Identifiers;
using EricksonLopez.Events.Registry;
using AwesomeAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace EricksonLopez.Events.Generators.Tests;

public static class EventConstants
{
    public const string OrderPlacedName = "test.order-placed";
    public const uint OrderPlacedVersion = 2;
    public const string OrderPlacedSource = "test-service";
}

[Trait("Category", "Unit")]
public sealed class EventIncrementalGeneratorTests
{
    private static string EnsureUsings(string source) => RoslynTestBed.EnsureUsings(source);
    private static string NormalizeCode(string code) => RoslynTestBed.NormalizeCode(code);

    [Fact]
    public void Generator_ShouldDiscoverEventsAndEmitGeneratedRegistry_WithExactSourceAndRuntimeExecution()
    {
        var sourceCode = @"
namespace TestApp
{
    public static class EventConstants
    {
        public const string OrderPlacedName = ""test.order-placed"";
    }

    [EventName(EventConstants.OrderPlacedName)]
    [EventVersion(2)]
    [EventSource(""test-service"")]
    public sealed record TestOrderPlaced(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;

    public sealed record PlainDiscoveredEvent(EventId Id, DateTimeOffset OccurredAt) : IEvent;

    [EventName(""test.annotated-only"")]
    public sealed class AnnotatedOnlyClass
    {
    }

    public abstract class AbstractEventClass : IEvent
    {
        public abstract EventId Id { get; }
        public abstract DateTimeOffset OccurredAt { get; }
    }

    public interface IEventSubInterface : IEvent
    {
    }

    public sealed class NonEventClass
    {
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode);
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out var outputCompilation,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(1);

        var generatedSource = runResult.GeneratedTrees[0].ToString();

        var expectedSource = @"// <auto-generated />
#nullable enable

namespace EricksonLopez.Events.Generated;

using System;
using System.Collections.Generic;
using EricksonLopez.Events.Identifiers;
using EricksonLopez.Events.Registry;

/// <summary>
/// Compile-time generated event registry containing zero-reflection descriptors.
/// </summary>
public static class GeneratedEventRegistry
{
    /// <summary>
    /// Creates an immutable <see cref=""IEventTypeRegistry""/> with all compile-time discovered event descriptors.
    /// </summary>
    public static IEventTypeRegistry CreateRegistry()
    {
        var descriptors = new List<EventTypeDescriptor>(3);

        descriptors.Add(new EventTypeDescriptor(
            typeof(global::TestApp.AnnotatedOnlyClass),
            new EventType(""test.annotated-only""),
            new EventVersion(1u),
            null));

        descriptors.Add(new EventTypeDescriptor(
            typeof(global::TestApp.PlainDiscoveredEvent),
            new EventType(""PlainDiscoveredEvent""),
            new EventVersion(1u),
            null));

        descriptors.Add(new EventTypeDescriptor(
            typeof(global::TestApp.TestOrderPlaced),
            new EventType(""test.order-placed""),
            new EventVersion(2u),
            ""test-service""));

        return new EventTypeRegistry(descriptors);
    }
}";

        NormalizeCode(generatedSource).Should().Be(NormalizeCode(expectedSource));

        // Runtime compilation and execution check via RoslynTestBed
        var asm = RoslynTestBed.EmitAndLoadAssembly(outputCompilation);
        var regType = asm.GetType("EricksonLopez.Events.Generated.GeneratedEventRegistry");
        regType.Should().NotBeNull();
        var createMethod = regType!.GetMethod("CreateRegistry", BindingFlags.Public | BindingFlags.Static);
        createMethod.Should().NotBeNull();

        var registry = createMethod!.Invoke(null, null) as IEventTypeRegistry;
        registry.Should().NotBeNull();
        registry!.GetAllDescriptors().Count.Should().Be(3);

        var orderType = asm.GetType("TestApp.TestOrderPlaced")!;
        registry.TryGetDescriptor(orderType, out var orderDesc).Should().BeTrue();
        orderDesc!.EventType.Value.Should().Be("test.order-placed");
        orderDesc.Version.Value.Should().Be(2u);
        orderDesc.Source.Should().Be("test-service");

        var annotatedType = asm.GetType("TestApp.AnnotatedOnlyClass")!;
        registry.TryGetDescriptor(annotatedType, out var annDesc).Should().BeTrue();
        annDesc!.EventType.Value.Should().Be("test.annotated-only");
        annDesc.Version.Value.Should().Be(1u);
        annDesc.Source.Should().BeNull();

        var plainType = asm.GetType("TestApp.PlainDiscoveredEvent")!;
        registry.TryGetDescriptor(plainType, out var plainDesc).Should().BeTrue();
        plainDesc!.EventType.Value.Should().Be("PlainDiscoveredEvent");
        plainDesc.Version.Value.Should().Be(1u);
        plainDesc.Source.Should().BeNull();
    }

    [Fact]
    public void Generator_Ordering_ShouldDeterministicallySortByFullTypeNameAscending()
    {
        var sourceCode = @"
namespace ZApp
{
    public sealed record ZetaEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
}

namespace AApp
{
    public sealed record AlphaEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
}

namespace MApp
{
    public sealed record BetaEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "SortCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out _);

        var generatedSource = runResult.GeneratedTrees[0].ToString();

        var posAlpha = generatedSource.IndexOf("global::AApp.AlphaEvent", StringComparison.Ordinal);
        var posBeta = generatedSource.IndexOf("global::MApp.BetaEvent", StringComparison.Ordinal);
        var posZeta = generatedSource.IndexOf("global::ZApp.ZetaEvent", StringComparison.Ordinal);

        posAlpha.Should().BeGreaterThan(0);
        posBeta.Should().BeGreaterThan(posAlpha);
        posZeta.Should().BeGreaterThan(posBeta);
    }

    [Fact]
    public void Generator_SemanticAttributes_WithoutSuffix_And_EmptyArguments()
    {
        var sourceCode = @"
namespace CustomAttrApp
{
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class EventName : Attribute { public EventName(string name) {} }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class EventVersion : Attribute { public EventVersion(uint version) {} }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class EventSource : Attribute { public EventSource(string source) {} }

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
    public class EmptyAttr : Attribute { }

    [EventName(""custom.nosuffix"")]
    [EventVersion(7)]
    [EventSource(""nosuffix-source"")]
    public sealed class NoSuffixEvent { }

    [EmptyAttr]
    [EventName]
    [EventVersion]
    [EventSource]
    public sealed record EmptyArgsEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "CustomAttrCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diags);

        diags.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(1);
        var generatedSource = runResult.GeneratedTrees[0].ToString();

        generatedSource.Should().Contain("\"custom.nosuffix\"");
        generatedSource.Should().Contain("new EventVersion(7u)");
        generatedSource.Should().Contain("\"nosuffix-source\"");

        generatedSource.Should().Contain("\"EmptyArgsEvent\"");
        generatedSource.Should().Contain("new EventVersion(1u)");
    }

    [Fact]
    public void Generator_SemanticAttributes_WithZeroAndInvalidVersions()
    {
        var sourceCode = @"
namespace ZeroVerApp;

[EventName(""zero.version"")]
[EventVersion(0)]
public sealed record ZeroVersionEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "ZeroVerCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out _);

        var generatedSource = runResult.GeneratedTrees[0].ToString();

        generatedSource.Should().Contain("\"zero.version\"");
        generatedSource.Should().Contain("new EventVersion(1u)");
        generatedSource.Should().NotContain("new EventVersion(0u)");
    }

    [Fact]
    public void Generator_WithSyntaxFallback_WithoutAssemblyReferences_ShouldCoverAllSyntaxForms()
    {
        var sourceCode = @"
namespace FallbackApp;

[EventName(""fallback.one"")]
[EventVersion(3)]
[EventSource(""src-1"")]
public sealed class EventOne { }

[EventNameAttribute(""fallback.two"")]
[EventVersionAttribute(4)]
[EventSourceAttribute(""src-2"")]
public sealed class EventTwo { }

[Attributes.EventName(""fallback.three"")]
[Attributes.EventVersion(5)]
[Attributes.EventSource(""src-3"")]
public sealed class EventThree { }

[EricksonLopez.Events.Attributes.EventName(""fallback.four"")]
[EricksonLopez.Events.Attributes.EventVersion(6)]
[EricksonLopez.Events.Attributes.EventSource(""src-4"")]
public sealed class EventFour { }
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "FallbackCompilation", references: Array.Empty<MetadataReference>());
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out _);

        runResult.GeneratedTrees.Should().HaveCount(1);
        var generatedSource = runResult.GeneratedTrees[0].ToString();

        generatedSource.Should().Contain("\"fallback.one\"");
        generatedSource.Should().Contain("new EventVersion(3u)");
        generatedSource.Should().Contain("\"src-1\"");

        generatedSource.Should().Contain("\"fallback.two\"");
        generatedSource.Should().Contain("new EventVersion(4u)");
        generatedSource.Should().Contain("\"src-2\"");

        generatedSource.Should().Contain("\"fallback.three\"");
        generatedSource.Should().Contain("new EventVersion(5u)");
        generatedSource.Should().Contain("\"src-3\"");

        generatedSource.Should().Contain("\"fallback.four\"");
        generatedSource.Should().Contain("new EventVersion(6u)");
        generatedSource.Should().Contain("\"src-4\"");
    }

    [Fact]
    public void Generator_SyntaxFallback_EdgeCases_EmptyParenthesesAndZeroVersion()
    {
        var sourceCode = @"
namespace FallbackEdgeApp;

[EventName()]
[EventVersion()]
[EventSource()]
public sealed class EmptyParenthesesEvent { }

[EventName(""fallback.zero"")]
[EventVersion(0)]
[EventSource]
public sealed class ZeroSyntaxVersionEvent { }

[EventVersion(""not-a-number"")]
public sealed class InvalidVersionStringEvent { }
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "FallbackEdgeCompilation", references: Array.Empty<MetadataReference>());
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diags);

        diags.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(1);
        var generatedSource = runResult.GeneratedTrees[0].ToString();

        generatedSource.Should().Contain("\"fallback.zero\"");
        generatedSource.Should().Contain("new EventVersion(1u)");
        generatedSource.Should().NotContain("new EventVersion(0u)");
    }

    [Fact]
    public void Generator_WithDuplicateEventsInMultipleTrees_ShouldDeduplicate()
    {
        var source1 = @"
namespace TestApp;
public sealed record SharedEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
";
        var source2 = @"
namespace TestApp;
public sealed record AnotherEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
";

        var tree1 = CSharpSyntaxTree.ParseText(EnsureUsings(source1));
        var tree2 = CSharpSyntaxTree.ParseText(EnsureUsings(source2));

        var compilation = RoslynTestBed.CreateCompilation(new[] { tree1, tree2 }, "MultiTreeCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(1);
        var src = runResult.GeneratedTrees[0].ToString();
        src.Should().Contain("SharedEvent");
        src.Should().Contain("AnotherEvent");
    }

    [Fact]
    public void Generator_WithNoEvents_And_UnrelatedInterfaces_ShouldNotEmitSource()
    {
        var sourceCode = @"
namespace TestApp;

public sealed class RegularClass { }
public struct RegularStruct { }
public enum RegularEnum { A, B }

[Serializable]
public sealed class CustomAnnotatedClass { }

public sealed class DisposableClass : IDisposable
{
    public void Dispose() { }
}

public sealed class ComparableClass : IComparable
{
    public int CompareTo(object? obj) => 0;
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "EmptyCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_WithForeignIEventInterfaceOrUnrelatedContracts_ShouldNotEmitSource()
    {
        var sourceCode = @"
namespace ForeignNamespace
{
    public interface IEvent { }
}

namespace TestApp
{
    // Implements IEvent from ForeignNamespace, not EricksonLopez.Events.Contracts
    public sealed class ForeignEventClass : ForeignNamespace.IEvent
    {
    }

    // Implements IEventPublisher from EricksonLopez.Events.Contracts, but not IEvent
    public sealed class DummyPublisher : IEventPublisher
    {
        public ValueTask PublishAsync<TEvent>(TEvent eventInstance, CancellationToken cancellationToken = default) where TEvent : IEvent
        {
            return ValueTask.CompletedTask;
        }
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "ForeignInterfaceCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_SyntaxFallback_WithNonLiteralExpression_ShouldFallbackGracefully()
    {
        var sourceCode = @"
namespace FallbackNonLitApp;

public static class SomeConstants
{
    public const string Name = ""some.name"";
}

[EventName(SomeConstants.Name)]
public sealed class NonLiteralSyntaxEvent { }
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "NonLitFallbackCompilation", references: Array.Empty<MetadataReference>());
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_SemanticAttributes_WithNullArguments_ShouldFallbackToDefaults()
    {
        var sourceCode = @"
namespace NullArgsApp;

[EventName(null)]
[EventSource(null)]
public sealed record NullArgsEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "NullArgsCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diags);

        diags.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(1);
        var generatedSource = runResult.GeneratedTrees[0].ToString();

        generatedSource.Should().Contain("\"NullArgsEvent\"");
        generatedSource.Should().Contain("new EventVersion(1u)");
    }

    [Fact]
    public void Generator_WithGlobalNamespaceIEvent_ShouldNotEmitSource()
    {
        var sourceCode = @"
// Global namespace IEvent
public interface IEvent { }

namespace TestApp
{
    public sealed class GlobalEventClass : IEvent
    {
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "GlobalInterfaceCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_WithMultipleHandlersAndMultipleInterfaces_ShouldEmitAllRegistrations()
    {
        var sourceCode = @"
namespace MultiApp
{
    public sealed record EventA(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;
    public sealed record EventB(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;

    public sealed class DualHandler : IEventHandler<EventA>, IEventHandler<EventB>
    {
        public ValueTask HandleAsync(EventA evt, System.Threading.CancellationToken ct = default) => ValueTask.CompletedTask;
        public ValueTask HandleAsync(EventB evt, System.Threading.CancellationToken ct = default) => ValueTask.CompletedTask;
    }

    public abstract class AbstractHandler : IEventHandler<EventA>
    {
        public abstract ValueTask HandleAsync(EventA evt, System.Threading.CancellationToken ct = default);
    }

    public interface IHandlerInterface : IEventHandler<EventA> { }

    public class GenericHandler<T> : IEventHandler<EventA>
    {
        public ValueTask HandleAsync(EventA evt, System.Threading.CancellationToken ct = default) => ValueTask.CompletedTask;
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "MultiHandlerCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var extensionsTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.Contains("GeneratedEventServiceCollectionExtensions"));
        extensionsTree.Should().NotBeNull();

        var source = extensionsTree!.ToString();
        source.Should().Contain("typeof(IEventHandler<global::MultiApp.EventA>)");
        source.Should().Contain("typeof(IEventHandler<global::MultiApp.EventB>)");
        source.Should().Contain("typeof(global::MultiApp.DualHandler)");
        source.Should().NotContain("AbstractHandler");
        source.Should().NotContain("IHandlerInterface");
        source.Should().NotContain("GenericHandler");
    }

    [Fact]
    public void Generator_WithOtherNamespaceIEventHandler_ShouldSkip()
    {
        var sourceCode = @"
namespace OtherNamespace
{
    public interface IEventHandler<T> { }
}

namespace AppWithOtherHandler
{
    public sealed record LocalEvent(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;

    public sealed class OtherNamespaceHandler : OtherNamespace.IEventHandler<LocalEvent>
    {
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "OtherHandlerCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        // Generates only registry (1 tree), no handlers extension
        runResult.GeneratedTrees.Should().HaveCount(1);
    }

    [Fact]
    public void Generator_WithHandlers_ShouldEmitExactSource_AndExecuteRuntimeDIChaining()
    {
        var sourceCode = @"
using System.Threading.Tasks;

namespace HandlerApp
{
    public sealed record OrderPlaced(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;

    public sealed class OrderPlacedHandler : IEventHandler<OrderPlaced>
    {
        public ValueTask HandleAsync(OrderPlaced eventInstance, System.Threading.CancellationToken cancellationToken = default) =>
            ValueTask.CompletedTask;
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "ExactHandlerCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out var outputCompilation,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var extensionsTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.Contains("GeneratedEventServiceCollectionExtensions"));
        extensionsTree.Should().NotBeNull();

        var generatedSource = extensionsTree!.ToString();

        var expectedSource = @"// <auto-generated />
#nullable enable

namespace Microsoft.Extensions.DependencyInjection;

using System;
using EricksonLopez.Events.Contracts;
using Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Compile-time generated DI extension methods for discovered event handlers.
/// </summary>
public static class GeneratedEventServiceCollectionExtensions
{
    /// <summary>
    /// Automatically registers all compile-time discovered event handlers in the service collection.
    /// </summary>
    /// <param name=""services"">The service collection.</param>
    /// <param name=""lifetime"">The service lifetime (defaults to Transient).</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddGeneratedEventHandlers(
        this IServiceCollection services,
        ServiceLifetime lifetime = ServiceLifetime.Transient)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.Add(new ServiceDescriptor(
            typeof(IEventHandler<global::HandlerApp.OrderPlaced>),
            typeof(global::HandlerApp.OrderPlacedHandler),
            lifetime));

        return services;
    }
}
";

        NormalizeCode(generatedSource).Should().Be(NormalizeCode(expectedSource));

        // Runtime check
        var asm = RoslynTestBed.EmitAndLoadAssembly(outputCompilation);
        var extType = asm.GetType("Microsoft.Extensions.DependencyInjection.GeneratedEventServiceCollectionExtensions");
        extType.Should().NotBeNull();
        var addMethod = extType!.GetMethod("AddGeneratedEventHandlers", BindingFlags.Public | BindingFlags.Static);
        addMethod.Should().NotBeNull();

        var services = new ServiceCollection();
        var ret = addMethod!.Invoke(null, new object[] { services, ServiceLifetime.Transient });
        ret.Should().BeSameAs(services);
        services.Should().ContainSingle(sd =>
            sd.ServiceType.Name.StartsWith("IEventHandler") &&
            sd.ImplementationType!.Name == "OrderPlacedHandler" &&
            sd.Lifetime == ServiceLifetime.Transient);
    }

    [Fact]
    public void Generator_Ordering_Handlers_ShouldDeterministicallySortByHandlerNameAscending()
    {
        var sourceCode = @"
namespace SortApp
{
    public sealed record OrderPlaced(EventId Id, DateTimeOffset OccurredAt) : IDomainEvent;

    public sealed class ZetaHandler : IEventHandler<OrderPlaced>
    {
        public ValueTask HandleAsync(OrderPlaced evt, System.Threading.CancellationToken ct = default) => ValueTask.CompletedTask;
    }

    public sealed class AlphaHandler : IEventHandler<OrderPlaced>
    {
        public ValueTask HandleAsync(OrderPlaced evt, System.Threading.CancellationToken ct = default) => ValueTask.CompletedTask;
    }
}
";

        var compilation = RoslynTestBed.CreateCompilation(sourceCode, "SortHandlersCompilation");
        var runResult = RoslynTestBed.RunGenerator(
            new EventIncrementalGenerator(),
            compilation,
            out _,
            out var diagnostics);

        diagnostics.Should().BeEmpty();
        var extensionsTree = runResult.GeneratedTrees.FirstOrDefault(t => t.FilePath.Contains("GeneratedEventServiceCollectionExtensions"));
        extensionsTree.Should().NotBeNull();

        var source = extensionsTree!.ToString();
        var posAlpha = source.IndexOf("global::SortApp.AlphaHandler", StringComparison.Ordinal);
        var posZeta = source.IndexOf("global::SortApp.ZetaHandler", StringComparison.Ordinal);

        posAlpha.Should().BeGreaterThan(0);
        posZeta.Should().BeGreaterThan(posAlpha);
    }
}


