<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework></TargetFramework>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>System.Text.Json Native AOT converters and serialization adapters for EricksonLopez.Events.</Description>
    <PackageTags>$(CommonPackageTags);serialization;system-text-json;json;json-converter;envelope;guid-v7</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Events\EricksonLopez.Events.csproj" />
  </ItemGroup>

</Project>
