<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Events\EricksonLopez.Events.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Events.OpenTelemetry\EricksonLopez.Events.OpenTelemetry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenTelemetry" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\EricksonLopez.Events.UnitTests\Common\ActivityTestScope.cs" Link="Common\ActivityTestScope.cs" />
    <Compile Include="..\EricksonLopez.Events.UnitTests\Common\MeterTestScope.cs" Link="Common\MeterTestScope.cs" />
    <Compile Include="..\EricksonLopez.Events.UnitTests\Common\DiagnosticsTestFixture.cs" Link="Common\DiagnosticsTestFixture.cs" />
  </ItemGroup>
</Project>

