<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Application\ECommerce.Application.csproj" />
    <ProjectReference Include="..\..\..\src\EricksonLopez.Events\EricksonLopez.Events.csproj" />
    <ProjectReference Include="..\..\..\src\EricksonLopez.Events.Serialization.SystemTextJson\EricksonLopez.Events.Serialization.SystemTextJson.csproj" />
    <ProjectReference Include="..\..\..\src\EricksonLopez.Events.CloudEvents\EricksonLopez.Events.CloudEvents.csproj" />
  </ItemGroup>

</Project>
